Fixing conflict error coming from home manager
           error: The option `home-manager.users.dwilliams.home.username' has conflicting definition values:
       - In `/nix/store/c9asdiqw1rf5qwdjz26f57hp68ppb8fc-source/flake.nix': "your-username"
       - In `/nix/store/7j28pjv6h1zzpi09qdilmrpqy357rlz8-source/nixos/common.nix': "dwilliams"
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
Command 'nix --extra-experimental-features 'nix-command flakes' build --print-out-paths '.#nixosConfigurations."hyprland-btw".config.system.build.toplevel' --no-link --option accept-flake-config true --refresh' returned non-zero exit status 1.

 On branch dev
 Your branch is up to date with 'origin/dev'.

 Changes to be committed:
	modified:   README.md
	modified:   home.nix
	modified:   install.sh